<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKOvkkOH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKOvkkOH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKOvkkOH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKOvkkOH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKOvkkOH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KOvkkOH',
    'container.build_id' => '671c390b',
    'container.build_time' => 1559572257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKOvkkOH');
